#############################################################
#
## Makefile for building hnstest.exe with MingW32 (GCC-3.2)
## Use: make -f Makefile.m32
#
########################################################
CXX = g++
CC = gcc
LD = g++

# Where to find the hns source code; needed because the tests use library-internal headers
HNS_SRC_DIR = ..
# Where to find the built hns static library
HNS_BLD_DIR = ..
HNSLIB = $(HNS_BLD_DIR)/libhns.a
GMOCK_DIR = gmock-1.8.0
CPPFLAGS = -I$(HNS_SRC_DIR) -I$(GMOCK_DIR) -DHNS_STATICLIB
CXXFLAGS = -Wall $(PTHREAD_CFLAGS) -std=gnu++11
LDFLAGS =
LDLIBS = -lwsock32

# Makefile.inc provides the TESTSOURCES and TESTHEADERS defines
include Makefile.inc

OBJS := $(patsubst %.cc,%.o,$(strip $(TESTSOURCES)))
FUZZOBJS := $(patsubst %.c,%.o,$(strip $(FUZZSOURCES)))
FUZZNAMEOBJS := $(patsubst %.c,%.o,$(strip $(FUZZNAMESOURCES)))
DNSDUMPOBJS := $(patsubst %.cc,%.o,$(strip $(DUMPSOURCES)))

all: hnstest.exe hnsfuzz.exe hnsfuzzname.exe dnsdump.exe

hnstest.exe: $(OBJS) gmock-gtest-all.o
	$(LD) $(LDFLAGS) -o $@ $^  -L$(HNS_BLD_DIR) -lhns $(LDLIBS)

hnsfuzz.exe: $(FUZZOBJS)
	$(LD) $(LDFLAGS) -o $@ $^  -L$(HNS_BLD_DIR) -lhns $(LDLIBS)

hnsfuzzname.exe: $(FUZZNAMEOBJS)
	$(LD) $(LDFLAGS) -o $@ $^  -L$(HNS_BLD_DIR) -lhns $(LDLIBS)

dnsdump.exe: $(DNSDUMPOBJS)
	$(LD) $(LDFLAGS) -o $@ $^  -L$(HNS_BLD_DIR) -lhns $(LDLIBS)

$(OBJS): $(TESTHEADERS)

.cc.o:
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $<
.c.o:
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $<
gmock-gtest-all.o: $(GMOCK_DIR)/gmock-gtest-all.cc
	$(CXX) -I$(GMOCK_DIR) $(CPPFLAGS) $(CXXFLAGS) -c $<

test: hnstest.exe
	./hnstest.exe
vtest: hnstest.exe
	./hnstest.exe -v

clean:
	$(RM) $(OBJS) gmock-gtest-all.o hnstest.exe hnsfuzz.exe hnsfuzzname.exe dnsdump.exe


